"""Automatically generated by Nx."""

# * Import and expose progress utilities
# * Import and expose error handling utilities
from .error_utils import (
    ChunkingError,
    ConfigError,
    GitError,
    LLMConnectionError,
    LLMModelNotFoundError,
    LLMModelNotLoadedError,
    LLMProviderError,
    LLMResponseError,
    TemplateError,
    ToolkitError,
    convert_exception,
    error_handler,
    handle_error,
)
from .progress_utils import (
    indeterminate_progress,
    progress_bar,
    spinner,
    with_progress,
    with_spinner,
)

# * Import and expose template utilities
from .template_utils import (
    enrich_template_with_git_context,
    load_template,
)

# * Export all the utilities
__all__ = [
    # Progress utilities
    "progress_bar",
    "spinner",
    "with_spinner",
    "with_progress",
    "indeterminate_progress",
    # Error handling utilities
    "ToolkitError",
    "ConfigError",
    "GitError",
    "LLMProviderError",
    "LLMConnectionError",
    "LLMModelNotFoundError",
    "LLMModelNotLoadedError",
    "LLMResponseError",
    "ChunkingError",
    "TemplateError",
    "handle_error",
    "error_handler",
    "convert_exception",
    # Template utilities
    "load_template",
    "enrich_template_with_git_context",
]
